# SPDX-FileCopyrightText: 2023-2026, NORCE Research AS
# SPDX-License-Identifier: GPL-3.0

"""Run OPM Flow simulations generated by pyopmnearwell.

The module builds the Flow command from the shared configuration and executes it
in the configured simulation-output directory.
"""

import os
import subprocess


def simulations(dic):
    """Run OPM Flow for a generated pyopmnearwell deck.

    Missing ``foutp`` and ``mode`` values are initialized before the simulator
    command is assembled and executed.

    Parameters
    ----------
    dic : dict
        Shared configuration containing ``flow``, ``fol``, ``fprep``, ``foutp``,
        ``runname``, and optional runtime values.

    Raises
    ------
    subprocess.CalledProcessError
        If OPM Flow exits with a nonzero status.
    """
    if "foutp" not in dic:
        dic["foutp"] = f"{dic['fol']}/output"
    if "mode" not in dic:
        dic["mode"] = "all"
    os.makedirs(dic["foutp"], exist_ok=True)
    command = (
        f"{dic['flow']} --output-dir={dic['foutp']} "
        f"{dic['fprep']}/{dic['runname'].upper()}.DATA"
    )
    subprocess.run(
        command,
        cwd=dic["foutp"],
        shell=True,
        check=True,
    )
