name: Run pyopmnearwell

on:
 pull_request:
   
jobs:
  run-pyopmnearwell-local:
    permissions:
      contents: read
    timeout-minutes: 60
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    
    - name: Install Flow Simulator
      run: |
        sudo apt-get update
        sudo apt-get install software-properties-common mpi-default-bin
        sudo apt-add-repository ppa:opm/ppa
        sudo apt-get update
        sudo apt-get install libopm-simulators-bin

    - name: Install pyopmnearwell and python requirements
      run: |
        python3 -m venv vpyopmnearwell
        . vpyopmnearwell/bin/activate
        echo "$PWD/vpyopmnearwell/bin" >> $GITHUB_PATH
        pip install --upgrade pip setuptools wheel
        pip install .
        pip install tensorflow
        pip install -r dev-requirements.txt
        
    - name: Check code style and linting 
      run: |
        black --target-version py312 src/ tests/ --check
        pylint src/ tests/
        ruff check src/ tests/
        mypy --ignore-missing-imports src/ tests/
      
    - name: Run the tests
      run: |
        pytest --cov=pyopmnearwell --cov-report term-missing --basetemp=test_outputs tests/ --exitfirst

    - name: Build documentation
      run: |
        pushd docs
        make html SPHINXOPTS="-W"
